---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-metrics-exporter
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: harbortokensecret
type: Opaque
data:
  token: ENTER_YOUR_API_TOKEN

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: harbor-metrics-exporter
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - endpoints
    verbs: ["get", "list"]
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: harbor-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-metrics-exporter
subjects:
  - kind: ServiceAccount
    name: harbor-metrics-exporter
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-metrics-exporter
  namespace: default
  labels:
    app: harbor-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-metrics-exporter
  template:
    metadata:
      labels:
        app: harbor-metrics-exporter
    spec:
      serviceAccountName: harbor-metrics-exporter
      containers:
        - image: dev.registry.pivotal.io/software-distribution/harbor-metrics:scratch
          imagePullPolicy: Never
          name: harbor-metrics-exporter
          env:
            - name: HARBOR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: harbortokensecret
                  key: token
            - name: REGISTRY_SERVER
              value: "dev.registry.pivotal.io"
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: http-metrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: harbor-metrics-exporter
  namespace: default
  labels:
    app: harbor-metrics-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
  selector:
    app: harbor-metrics-exporter
